# Define any constants you want to use in your project
DATABASE_URL="http://127.0.0.1:5000" # Example constant

# API NAMES
CREATE_BEER_COMPANY = "CREATE_BEER_COMPANY"
GET_BEER_COMPANY = "GET_BEER_COMPANY"
UPDATE_BEER_COMPANY = "UPDATE_BEER_COMPANY"
DELETE_BEER_COMPANY = "DELETE_BEER_COMPANY"
LIST_BEER_COMPANIES = "LIST_BEER_COMPANIES"

# HTTP METHODS
GET = "GET"
POST = "POST"
PUT = "PUT"
DELETE = "DELETE"